function world_images() {
  var table_images = document.getElementById('table_images');
  table_images.innerHTML = '<table class="table_images"><tr><td><img src="img/1.jpg" class="img"><a href="img/1.jpg"  class="download"  download="1" >Download image</a></td>  <td><img src="img/2.jpg" class="img"><a href="img/2.jpg"  class="download" download="2">Download image</a></td></tr><tr><td><img src="img/3.jpg" class="img"><a href="img/3.jpg"  class="download" download="3">Download image</a></td><td><img src="img/4.jpg" class="img"><a href="img/4.jpg"   class="download" download="4">Download image</a></td></tr><tr>  <td><img src="img/5.jpg" class="img"><a href="img/5.jpg"  class="download" download="5">Download image</a></td><td><img src="img/6.jpg" class="img"><a href="img/6.jpg"  class="download" download="6">Download image</a></td></tr></table>';
}
function sity_images() {
  var table_images = document.getElementById('table_images');
  table_images.innerHTML = '<table class="table_images"><tr><td><img src="img/2_1.jpg" class="img"><a href="img/2_1.jpg"  download="2_1" class="download">Download image</a></td>  <td><img src="img/2_2.jpg" class="img"><a href="img/2_2.jpg"  download="2_2" class="download">Download image</a></td></tr><tr><td><img src="img/2_3.jpg" class="img"><a href="img/2_3.jpg"  download="2_3" class="download">Download image</a></td><td><img src="img/2_4.jpg" class="img"><a href="img/2_4.jpg"  download="2_4"  class="download">Download image</a></td></tr><tr>  <td><img src="img/2_5.jpg" class="img"><a href="img/2_5.jpg" download="2_5" class="download">Download image</a></td><td><img src="img/2_6.jpg" class="img"><a href="img/2_6.jpg"  download="2_6" class="download">Download image</a></td></tr></table>';
}
function space_images() {
  var table_images = document.getElementById('table_images');
  table_images.innerHTML = '<table class="table_images"><tr><td><img src="img/3_1.jpg" class="img"><a href="img/3_1.jpg" download="3_1" class="download">Download image</a></td>  <td><img src="img/3_2.jpg" class="img"><a href="img/3_2.jpg" download="3_2" class="download">Download image</a></td></tr><tr><td><img src="img/3_3.jpg" class="img"><a href="img/3_3.jpg" download="3_3" class="download">Download image</a></td><td><img src="img/3_4.jpg" class="img"><a href="img/3_4.jpg" download="3_4"  class="download">Download image</a></td></tr><tr>  <td><img src="img/3_5.jpg" class="img"><a href="img/3_5.jpg" download="3_5" class="download">Download image</a></td><td><img src="img/3_6.jpg" class="img"><a href="img/3_6.jpg" download="3_6" class="download">Download image</a></td></tr></table>';
}
